# Generated by Django 5.2.11 on 2026-04-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('patient_type', models.CharField(choices=[('walkin', 'Walk-in'), ('registered', 'Registered')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('bill_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_tests', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('complete', 'Complete')], max_length=10)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.patient')),
            ],
        ),
    ]
