# Generated by Django 5.2.11 on 2026-04-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.CharField(max_length=50, unique=True)),
                ('agency_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('address_line_3', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('is_collection_location', models.BooleanField(default=False)),
                ('is_processing_location', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=50)),
                ('parameter_name', models.CharField(max_length=100)),
                ('parameter_print_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_value', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text')], max_length=10)),
                ('parameter_unit', models.CharField(choices=[('ml', 'ML'), ('g_dl', 'g/dL'), ('mg_dl', 'mg/dL')], max_length=20)),
                ('delta_check_percentage', models.FloatField(blank=True, null=True)),
                ('technique_used', models.CharField(blank=True, max_length=100, null=True)),
                ('skip_numeric_result_entry', models.BooleanField(default=False)),
                ('execution_calendar_linking', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Parameter',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=50, unique=True)),
                ('sample_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_code', models.CharField(max_length=50, unique=True)),
                ('tube_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='restapi.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyClinicLinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_links', to='restapi.agency')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_links', to='restapi.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='clinics',
            field=models.ManyToManyField(related_name='agencies', to='restapi.clinic'),
        ),
        migrations.CreateModel(
            name='Machine_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_parameter_code', models.CharField(max_length=50)),
                ('machine_parameter_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_parameters', to='restapi.machine')),
            ],
            options={
                'db_table': 'Machine_Parameter',
            },
        ),
        migrations.CreateModel(
            name='ParameterFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_expression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='restapi.parameter')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=20)),
                ('min_ref', models.FloatField()),
                ('max_ref', models.FloatField()),
                ('min_authz', models.FloatField()),
                ('max_authz', models.FloatField()),
                ('is_age_applicable', models.BooleanField(default=False)),
                ('age_lower_limit', models.IntegerField()),
                ('age_upper_limit', models.IntegerField()),
                ('improbable_value_1', models.FloatField(blank=True, null=True)),
                ('improbable_value_2', models.FloatField(blank=True, null=True)),
                ('is_reflex', models.BooleanField(default=False)),
                ('reflex_value_1', models.FloatField(blank=True, null=True)),
                ('reflex_value_2', models.FloatField(blank=True, null=True)),
                ('panic_value_1', models.FloatField(blank=True, null=True)),
                ('panic_value_2', models.FloatField(blank=True, null=True)),
                ('varying_ref_range', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_reference', to='restapi.machine')),
            ],
            options={
                'db_table': 'ParameterReferenceRange',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameterreferenceranger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='restapi.parameterreferencerange'),
        ),
        migrations.CreateModel(
            name='Pathology_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='restapi.service')),
            ],
            options={
                'db_table': 'Pathology_profile',
            },
        ),
        migrations.CreateModel(
            name='AgencyServiceLinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_services', to='restapi.agency')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.service')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='specializations',
            field=models.ManyToManyField(related_name='agencies', to='restapi.specialization'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=50, unique=True)),
                ('template_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('template_format', models.TextField()),
                ('pathologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='restapi.pathology_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=50, unique=True)),
                ('test_name', models.CharField(max_length=100)),
                ('print_name', models.CharField(blank=True, max_length=150, null=True)),
                ('service_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tube_name', models.CharField(blank=True, max_length=150, null=True)),
                ('test_completion_time', models.CharField(blank=True, max_length=10, null=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('suggestion_note', models.TextField(blank=True, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('report_type', models.CharField(choices=[('parameter', 'Parameter'), ('template', 'Template')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='restapi.category')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_service', to='restapi.service')),
                ('tube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_service', to='restapi.tube')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.AddField(
            model_name='pathology_profile',
            name='tests',
            field=models.ManyToManyField(to='restapi.test'),
        ),
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tests', to='restapi.test'),
        ),
        migrations.CreateModel(
            name='By_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_template_parameter', to='restapi.parameter')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_template_sample', to='restapi.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_template_test', to='restapi.test')),
            ],
            options={
                'db_table': 'By_Template',
            },
        ),
        migrations.CreateModel(
            name='By_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_parameter', to='restapi.parameter')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_parameter_sample', to='restapi.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_parameter_test', to='restapi.test')),
            ],
            options={
                'db_table': 'By_Parameter',
            },
        ),
    ]
