# Generated by Django 5.2.11 on 2026-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
