# Generated by Django 5.2.11 on 2026-05-05 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date_time', models.DateTimeField()),
                ('ship_no', models.CharField(max_length=50)),
                ('ship_from', models.CharField(max_length=100)),
                ('ship_to', models.CharField(max_length=100)),
                ('ship_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_date', models.DateTimeField()),
                ('Sample_no', models.CharField(max_length=100)),
                ('Sample_type', models.CharField(max_length=50)),
                ('test_code', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_mrn', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateTimeField()),
                ('received_no', models.CharField(max_length=100)),
                ('sample_no', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=50)),
                ('test_code', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_mrn', models.CharField(max_length=50)),
                ('ship_to', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentShipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateTimeField()),
                ('shipment_no', models.CharField(max_length=100)),
                ('sample_no', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=50)),
                ('test_code', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_mrn', models.CharField(max_length=50)),
                ('ship_to', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='patient',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='Patientname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_type',
        ),
        migrations.AddField(
            model_name='patient',
            name='MRN',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='cycle_ID',
            field=models.CharField(default='CYCLE001', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
