# Generated by Django 5.2.11 on 2026-05-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_parameter_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='restapi.clinic'),
        ),
        migrations.AlterField(
            model_name='template',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='restapi.clinic'),
        ),
        migrations.AlterField(
            model_name='test',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='restapi.clinic'),
        ),
        migrations.AlterField(
            model_name='tube',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubes', to='restapi.clinic'),
        ),
    ]
