# Generated by Django 5.2.11 on 2026-05-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_sample_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='pathologist',
        ),
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='restapi.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='template_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='template_for',
            field=models.CharField(choices=[('PATHOLOGY', 'Pathology'), ('RADIOLOGY', 'Radiology'), ('EXAMINATION', 'Examination'), ('INVESTIGATION', 'Investigation'), ('SURGERY', 'Surgery'), ('OUTCOME', 'Outcome')], default='PATHOLOGY', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='template',
            name='user_type',
            field=models.CharField(choices=[('PATHOLOGIST', 'Pathologist'), ('RADIOLOGIST', 'Radiologist')], default='PATHOLOGIST', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_format',
            field=models.CharField(choices=[('TEXT', 'Text'), ('FORM', 'Form')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='template',
            table='Template',
        ),
    ]
