# Generated by Django 5.2.11 on 2026-05-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_remove_template_pathologist_template_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='parameterreferencerange',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='skip_numeric_result_entry',
            new_name='is_skip_numeric_result_entry',
        ),
        migrations.RenameField(
            model_name='parameterreferencerange',
            old_name='varying_ref_range',
            new_name='varying_reference_range',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter_unit',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameterreferenceranger',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='category',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='improbable_value_1',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='improbable_value_2',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='panic_value_1',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='panic_value_2',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='reflex_value_1',
        ),
        migrations.RemoveField(
            model_name='parameterreferencerange',
            name='reflex_value_2',
        ),
        migrations.AddField(
            model_name='parameter',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='improbable_value_greater',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='improbable_value_less',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='machine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='panic_value_greater',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='panic_value_less',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='restapi.parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='reflex_value_greater',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='reflex_value_less',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parameterreferencerange',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='delta_check_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='execution_calendar_linking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_print_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='technique_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type_of_value',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text')], default='NUMERIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='age_lower_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='age_upper_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='max_authz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='max_ref',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='min_authz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='min_ref',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='parameter',
            table='parameters',
        ),
        migrations.AlterModelTable(
            name='parameterreferencerange',
            table='parameter_reference_ranges',
        ),
        migrations.DeleteModel(
            name='ParameterFormula',
        ),
    ]
