# Generated by Django 5.2.11 on 2026-05-28 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_rename_cycle_id_patient_cycle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField()),
                ('ship_time', models.TimeField()),
                ('dispatched_by', models.CharField(max_length=100)),
                ('ship_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.pendingshipment')),
            ],
        ),
    ]
