# Generated by Django 5.2.11 on 2026-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_sample_clinic_alter_template_clinic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.RemoveField(
            model_name='machineparameter',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='machineparameter',
            name='parameter',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_parameters',
            field=models.ManyToManyField(blank=True, related_name='machines', to='restapi.machineparameter'),
        ),
        migrations.AddField(
            model_name='machineparameter',
            name='machine_parameter_code',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machineparameter',
            name='machine_parameter_name',
            field=models.CharField(default='TEMP', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='machine',
            table=None,
        ),
    ]
