# Generated by Django 5.2.11 on 2026-06-03 14:57
# Generated by Django 5.2.11 on 2026-06-03 14:57
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0004_alter_machine_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiveSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ship_date", models.DateField()),
                ("ship_time", models.TimeField()),
                ("shipment_no", models.CharField(max_length=100)),
                ("specimen_no", models.CharField(max_length=100)),
                ("specimen_type", models.CharField(max_length=100)),
                ("test_code", models.CharField(max_length=100)),
                ("test_name", models.CharField(max_length=100)),
                ("service_name", models.CharField(max_length=200)),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_age", models.IntegerField()),
                ("patient_gender", models.CharField(max_length=20)),
                ("patient_code", models.CharField(max_length=100)),
                ("receive_date", models.DateField(blank=True, null=True)),
                ("receive_time", models.TimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("sub_optimal", models.BooleanField(default=False)),
                ("status", models.CharField(default="Shipped", max_length=50)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shipment_received",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receive_samples",
                        to="restapi.shipmentreceived",
                    ),
                ),
            ],
        ),
    ]
