# Generated by Django 5.2.11 on 2026-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_parameter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='by_template',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='by_template',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='by_template',
            name='test',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='is_skip_numeric_result_entry',
            new_name='skip_numeric_result_entry',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='delta_check_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_print_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type_of_value',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(choices=[('mg_dl', 'mg/dL'), ('g_dl', 'g/dL'), ('ml', 'mL'), ('mmol_l', 'mmol/L'), ('percent', '%')], default='mg_dl', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='By_Parameter',
        ),
        migrations.DeleteModel(
            name='By_Template',
        ),
    ]
