# Generated by Django 5.2.11 on 2026-06-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
