# Generated by Django 5.2.11 on 2026-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_remove_by_template_parameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='template',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='template',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='template',
            name='service',
        ),
        migrations.RemoveField(
            model_name='template',
            name='template_content',
        ),
        migrations.RemoveField(
            model_name='template',
            name='template_format',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user_type',
        ),
        migrations.AddField(
            model_name='template',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='template_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('TABLE', 'Table')], default='TEXT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='template_for',
            field=models.CharField(choices=[('TEST', 'Test'), ('PROFILE', 'Profile')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
        migrations.CreateModel(
            name='TemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_templates', to='restapi.parameter')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_parameters', to='restapi.template')),
            ],
            options={
                'db_table': 'template_parameters',
                'ordering': ['display_order'],
            },
        ),
    ]
