# Generated by Django 5.2.11 on 2026-06-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_test_test_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_categories', to='restapi.category'),
        ),
    ]
