# Generated by Django 5.2.11 on 2026-06-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0005_receivesample"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_name", models.CharField(max_length=200)),
                ("result_value", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("entered_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "result_status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receive_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_entries",
                        to="restapi.receivesample",
                    ),
                ),
            ],
        ),
    ]
