# Generated by Django 5.2.11 on 2026-06-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_test_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tests',
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='restapi.category'),
        ),
    ]
