# Generated by Django 5.2.11 on 2026-05-28 09:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_template_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='service',
        ),
        migrations.RemoveField(
            model_name='agencyservicelinking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='pathology_profile',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='test',
            name='tube',
        ),
        migrations.AddField(
            model_name='agencyservicelinking',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathology_profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 28, 9, 33, 15, 552201, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathology_profile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathology_profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pathology_profile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pathology_profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pathology_profile',
            name='tests',
            field=models.ManyToManyField(related_name='profiles', to='restapi.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='restapi.category'),
        ),
        migrations.AlterField(
            model_name='test',
            name='print_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='report_type',
            field=models.CharField(choices=[('PARAMETER', 'By Parameter'), ('TEMPLATE', 'By Template')], default='PARAMETER', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='tube_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='restapi.tube'),
        ),
        migrations.AlterModelTable(
            name='pathology_profile',
            table='pathology_profiles',
        ),
        migrations.AlterModelTable(
            name='test',
            table='tests',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
