# Generated by Django 5.2.11 on 2026-05-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_remove_test_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_tests', to='restapi.parameter')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='restapi.test')),
            ],
            options={
                'db_table': 'test_parameters',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_tests', to='restapi.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_samples', to='restapi.test')),
            ],
            options={
                'db_table': 'test_samples',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tests', to='restapi.template')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_templates', to='restapi.test')),
            ],
            options={
                'db_table': 'test_templates',
                'ordering': ['-id'],
            },
        ),
    ]
