# Generated by Django 5.2.11 on 2026-06-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_receivesample'),
        ('restapi', '0007_remove_category_tests_alter_test_category'),
    ]

    operations = [
    ]
