# Generated by Django 5.2.11 on 2026-05-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_testparameter_testsample_testtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='categories', to='restapi.test'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
