# Generated by Django 5.2.11 on 2026-06-07 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_merge_20260607_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.BigIntegerField(db_index=True)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_id', models.BigIntegerField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('patient_id', models.BigIntegerField(db_index=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_mrn', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cycle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_item_id', models.BigIntegerField(blank=True, null=True)),
                ('billing_source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_source_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('billing_source_code', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('test_service_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('test_service_code', models.CharField(blank=True, max_length=50, null=True)),
                ('test_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_from_package', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False)),
                ('agency_change_reason', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('INHOUSE', 'Inhouse'), ('OUTSOURCE', 'Outsource')], db_index=True, default='INHOUSE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('RESAMPLING', 'Resampling'), ('RESULT_PENDING', 'Result Pending'), ('RESULT_ENTERED', 'Result Entered'), ('AUTHORIZED', 'Authorized'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('barcode_value', models.CharField(max_length=100, unique=True)),
                ('specimen_no', models.CharField(max_length=100, unique=True)),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField()),
                ('collected_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='restapi.agency')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='restapi.sample')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='restapi.test')),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_order_id', 'test_service_id'], name='collections_work_or_8be316_idx'), models.Index(fields=['status', 'test_type'], name='collections_status_17d171_idx')],
                'constraints': [models.UniqueConstraint(fields=('work_order_id', 'billing_source_id', 'specimen_no'), name='unique_collection_per_order_test')],
            },
        ),
    ]
