# Generated by Django 5.2.11 on 2026-05-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_alter_category_options_remove_category_test_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathology_profile',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='pathology_profile',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='pathology_profile',
            name='service_name',
            field=models.CharField(default='Profile Service', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pathology_profile',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='restapi.test'),
        ),
    ]
