# Generated by Django 5.2.11 on 2026-06-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0006_resultentry"),
        ("restapi", "0009_collection"),
    ]

    operations = []
