# Generated by Django 5.2.11 on 2026-06-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_merge_0006_resultentry_0009_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivesample',
            old_name='shipment_received',
            new_name='shipment',
        ),
        migrations.AddField(
            model_name='pendingshipment',
            name='scheduled_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.collection'),
        ),
    ]
