# Generated by Django 5.2.11 on 2026-05-28 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_alter_pathology_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencycontact',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencyservicelinking',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencyservicelinking',
            name='test',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='clinics',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='specializations',
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_1_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_1_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_2_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='fax_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='specialization_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='agency',
            table='agencies',
        ),
        migrations.DeleteModel(
            name='AgencyClinicLinking',
        ),
        migrations.DeleteModel(
            name='AgencyContact',
        ),
        migrations.DeleteModel(
            name='AgencyServiceLinking',
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
