#Updated upstream
# Generated by Django 5.2.11 on 2026-06-09 06:06
# Generated by Django 5.2.11 on 2026-06-08 17:35
# Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
#Updated upstream
        ('restapi', '0011_rename_shipment_received_receivesample_shipment_and_more'),

        ("restapi", "0011_rename_shipment_received_receivesample_shipment_and_more"),
# Stashed changes
    ]

    operations = [
        migrations.AddField(
            model_name='pendingshipment',
            name='status',
            field=models.CharField(
                choices=[('Completed', 'Completed'), ('Pending', 'Pending')],
                default='Pending',
                max_length=50,
            ),
        ),
    ]
