# Generated by Django 5.2.11 on 2026-06-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_rename_shipment_received_receivesample_shipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivesample',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receivesample',
            name='resend_new_sample',
            field=models.BooleanField(default=False),
        ),
    ]
