# Generated by Django 5.2.11 on 2026-05-28 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_remove_agencycontact_agency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='is_active',
            new_name='status',
        ),
        migrations.AddField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='machine',
            table='machines',
        ),
        migrations.DeleteModel(
            name='Machine_Parameters',
        ),
    ]
