# Generated by Django 5.2.11 on 2026-06-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_pendingshipment_status'),
        ('restapi', '0012_receivesample_rejected_by_and_more'),
    ]

    operations = [
    ]
