# Generated by Django 5.2.11 on 2026-05-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_parameters', to='restapi.machine')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_machines', to='restapi.parameter')),
            ],
            options={
                'db_table': 'machine_parameters',
                'ordering': ['-id'],
            },
        ),
    ]
