# Generated by Django 5.2.11 on 2026-06-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0013_merge_20260609_1259"),
        ("restapi", "0013_merge_20260609_1417"),
    ]

    operations = []
