# Generated by Django 5.2.11 on 2026-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_merge_20260609_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyservice',
            name='profile',
        ),
        migrations.AddField(
            model_name='agencyservice',
            name='service_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
