# Generated by Django 5.2.11 on 2026-05-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_links', to='restapi.agency')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_links', to='restapi.clinic')),
            ],
            options={
                'db_table': 'agency_clinics',
            },
        ),
    ]
