# Generated by Django 4.2.30 on 2026-06-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_remove_agencyservice_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=20)),
                ('patient_code', models.CharField(max_length=100)),
                ('patient_type', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=200)),
                ('bill_no', models.CharField(max_length=100)),
                ('no_of_orders', models.IntegerField(default=0)),
                ('test_name', models.CharField(max_length=200)),
                ('result_status', models.CharField(default='Completed', max_length=50)),
                ('authorization_status', models.CharField(default='Pending', max_length=50)),
                ('authorized_by', models.CharField(blank=True, max_length=100, null=True)),
                ('authorized_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('result_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='restapi.resultentry')),
            ],
        ),
    ]
