# Generated by Django 5.2.11 on 2026-06-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='categories', to='restapi.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_tests', to='restapi.category'),
        ),
    ]
