# Generated by Django 5.2.11 on 2026-05-29 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_alter_agency_uuid_alter_category_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='restapi.clinic'),
            preserve_default=False,
        ),
    ]
