# Generated by Django 5.2.11 on 2026-05-29 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0019_machine_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathology_profile',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='restapi.clinic'),
            preserve_default=False,
        ),
    ]
