# Generated by Django 5.2.11 on 2026-05-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0020_pathology_profile_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mrn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cycle_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PendingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('sample_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sample_type', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine')], default='Blood', max_length=50)),
                ('test_code', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_shipments', to='restapi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField()),
                ('ship_time', models.TimeField()),
                ('dispatched_by', models.CharField(max_length=100)),
                ('ship_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.pendingshipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentShipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateTimeField()),
                ('shipment_no', models.CharField(max_length=100, unique=True)),
                ('ship_to', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipped_records', to='restapi.pendingshipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateTimeField()),
                ('received_no', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50)),
                ('result', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_records', to='restapi.shipmentshipped')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date_time', models.DateTimeField()),
                ('ship_from', models.CharField(max_length=100)),
                ('ship_to', models.CharField(max_length=100)),
                ('ship_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='restapi.shipmentshipped')),
            ],
        ),
    ]
