# Backup of conflicting migration
# Generated by Django 5.2.11 on 2026-05-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_activitylogs_pendingshipment_shipmentreceived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cycle_ID',
            new_name='cycle_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Patientname',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='pendingshipment',
            old_name='Order_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='activitylogs',
            name='ship_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='MRN',
        ),
        migrations.RemoveField(
            model_name='pendingshipment',
            name='Sample_no',
        ),
        migrations.RemoveField(
            model_name='pendingshipment',
            name='Sample_type',
        ),
        migrations.RemoveField(
            model_name='pendingshipment',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='pendingshipment',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='pendingshipment',
            name='patient_mrn',
        ),
        migrations.RemoveField(
            model_name='pendingshipment',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='patient_mrn',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='sample_no',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='ship_to',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='test_code',
        ),
        migrations.RemoveField(
            model_name='shipmentreceived',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='patient_mrn',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='sample_no',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='test_code',
        ),
        migrations.RemoveField(
            model_name='shipmentshipped',
            name='test_name',
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='shipped_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='restapi.shipmentshipped'),
        ),
        migrations.AddField(
            model_name='pendingshipment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_shipments', to='restapi.patient'),
        ),
        migrations.AddField(
            model_name='shipmentreceived',
            name='shipped_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_records', to='restapi.shipmentshipped'),
        ),
        migrations.AddField(
            model_name='shipmentshipped',
            name='pending_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipped_records', to='restapi.pendingshipment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shipmentreceived',
            name='received_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipmentreceived',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shipmentshipped',
            name='shipment_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pendingshipment',
            name='sample_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pendingshipment',
            name='sample_type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine')], default='Blood', max_length=50),
        ),
    ]
